// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/discord-bot.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/workflows.ts";
import * as $$$$$$$$$$$4 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Hero.tsx";
import * as $$$$$$1 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Hero.tsx": $$$$$$0,
    "site/sections/Theme/Theme.tsx": $$$$$$1,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/discord-bot.ts": $$$$$$$$$$$1,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$2,
    "site/apps/deco/workflows.ts": $$$$$$$$$$$3,
    "site/apps/site.ts": $$$$$$$$$$$4,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
